name: shopper
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - aioice==0.10.2
      - aiortc==1.14.0
      - altair==5.5.0
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - attrs==25.4.0
      - av==16.0.1
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - deepface==0.0.95
      - dnspython==2.8.0
      - filelock==3.20.0
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - h5py==3.15.1
      - idna==3.11
      - ifaddr==0.2.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - lz4==4.4.5
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - mtcnn==1.0.0
      - namex==0.1.0
      - narwhals==2.12.0
      - networkx==3.4.2
      - numpy==2.2.6
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - protobuf==6.33.1
      - psutil==7.1.3
      - pyarrow==21.0.0
      - pycparser==2.23
      - pydeck==0.9.1
      - pyee==13.0.0
      - pygments==2.19.2
      - pylibsrtp==1.0.0
      - pyopenssl==25.3.0
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - retina-face==0.0.17
      - rich==14.2.0
      - rpds-py==0.29.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8
      - streamlit==1.51.0
      - streamlit-autorefresh==1.0.1
      - streamlit-webrtc==0.64.5
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - tf-keras==2.20.1
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.9.1
      - torchvision==0.24.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ultralytics==8.3.229
      - ultralytics-thop==2.0.18
      - urllib3==2.5.0
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - wrapt==2.0.1

